{{- $webapp := .Values.georchestra.datadirsync  -}}
{{- if $webapp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-datadirsync
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datadirsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "georchestra.fullname" . }}-datadirsync
  template:
    metadata:
      labels:
        app: {{ include "georchestra.fullname" . }}-datadirsync
    spec:
      serviceAccountName: {{ include "georchestra.fullname" . }}-datadirsync-serviceaccount
      securityContext:
        fsGroup: 1001
      containers:
      - name: agent
        image: {{ $webapp.image }}
        env:
        - name: GIT_REPO_URL
          value: "{{ .Values.georchestra.datadir.git.url }}"
        - name: GIT_BRANCH
          value: "{{ .Values.georchestra.datadir.git.ref }}"
        - name: POLL_INTERVAL
          value: "{{ $webapp.pollInterval }}"
        - name: ROLLOUT_DEPLOYMENTS
          value: |
            {{ $prefix := include "georchestra.fullname" . -}}
            {{ $suffixes := $webapp.deploymentSuffixNameList -}}
            {{ $deployments := list -}}
            {{- range $suffix := $suffixes }}
            {{ $deployments = append $deployments (printf "%s-%s" $prefix $suffix) }}
            {{- end -}}
            {{- join ", " $deployments }}
        - name: ROLLOUT_NAMESPACE
          value: "{{ .Release.Namespace }}"
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - name: GIT_SSH_COMMAND
          value: ssh -i /id_rsa -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking=no"
        volumeMounts:
        - name: ssh-secret
          mountPath: /id_rsa
          # It's assumed that a subpath ssh-privatekey is in the secret (with the content of the file)
          subPath: ssh-privatekey
          readOnly: true
      volumes:
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0440
      {{- end }}
{{- end }}
