version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
